<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \App\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'idevento', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'hora', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'asistentes', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'salonIdsalon', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'menuIdmenu'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'idevento', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'hora', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'asistentes', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'salonIdsalon', '' . "\0" . 'App\\Entity\\Evento' . "\0" . 'menuIdmenu'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdevento(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdevento();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdevento', []);

        return parent::getIdevento();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(string $tipo): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(?string $descripcion): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getHora(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHora', []);

        return parent::getHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setHora(\DateTimeInterface $hora): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHora', [$hora]);

        return parent::setHora($hora);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsistentes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsistentes', []);

        return parent::getAsistentes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsistentes(string $asistentes): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsistentes', [$asistentes]);

        return parent::setAsistentes($asistentes);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalonIdsalon(): ?\App\Entity\Salon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalonIdsalon', []);

        return parent::getSalonIdsalon();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalonIdsalon(?\App\Entity\Salon $salonIdsalon): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalonIdsalon', [$salonIdsalon]);

        return parent::setSalonIdsalon($salonIdsalon);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuIdmenu(): ?\App\Entity\Menu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuIdmenu', []);

        return parent::getMenuIdmenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuIdmenu(?\App\Entity\Menu $menuIdmenu): \App\Entity\Evento
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuIdmenu', [$menuIdmenu]);

        return parent::setMenuIdmenu($menuIdmenu);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
