<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK8GL3bO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK8GL3bO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK8GL3bO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK8GL3bO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK8GL3bO\App_KernelDevDebugContainer([
    'container.build_hash' => 'K8GL3bO',
    'container.build_id' => '3ba02b8c',
    'container.build_time' => 1591696954,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK8GL3bO');
